server:
  port: 11451
spring:
  application:
    name: yuni-core
  datasource:
    url: jdbc:mysql://localhost:3306/yuni2_cms?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: yuni-core
    logger: slf4j
    qosEnable: true
    qosPort: 11461
    qosAcceptForeignIp: false
  protocol:
    name: tri
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

bots:
  config: bots.yml

master: 2937818202